src/clinical/Controllers/AtencionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using clinical.Data;
using clinical.Models;
using clinical.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;

namespace clinical.Controllers
{
    [Authorize]
    public class AtencionesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private ApplicationUser _user;

        public AtencionesController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            var userId = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            _user = _context.Users.FirstOrDefault(u => u.Id == userId);
        }

        // GET: Atenciones
        public async Task<IActionResult> Index()
        {
            return View(await _context.Atencion.ToListAsync());
        }

        // GET: Atenciones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var atencion = await _context.Atencion.SingleOrDefaultAsync(m => m.Id == id);
            if (atencion == null)
            {
                return NotFound();
            }

            return View(atencion);
        }

        // GET: Atenciones/Create
        public IActionResult _Create(int pacienteId)
        {
            var paciente = _context.Paciente.SingleOrDefault(m => m.Id == pacienteId);
            if (paciente == null)
            {
                return NotFound();
            }
            ViewBag.PacienteId = pacienteId;
            ViewBag.Doctores = new DoctoresHelper(_context, _user.IdEmpresa).SelectDoctores(paciente.DoctorId);
            ViewBag.Paciente = paciente;
            return View();
        }

        // GET: Atenciones/Create
        public IActionResult Create(int pacienteId)
        {
            ViewBag.PacienteId = pacienteId;
            return View();
        }

        // POST: Atenciones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Comentario,DoctorId,Fecha,PacienteId,TimeStamp,Tipo")] Atencion atencion)
        {
            if (ModelState.IsValid)
            {
                atencion.TimeStamp = DateTime.Now;
                _context.Add(atencion);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Pacientes", new { id = atencion.PacienteId });
            }
            return RedirectToAction("Details", "Pacientes", new { id = atencion.PacienteId });
        }

        // GET: Atenciones/Create
        public async Task<IActionResult> _Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var atencion = await _context.Atencion.Include(a => a.Paciente).SingleOrDefaultAsync(m => m.Id == id);
            if (atencion == null)
            {
                return NotFound();
            }
            ViewBag.PacienteId = atencion.PacienteId;
            ViewBag.Doctores = new DoctoresHelper(_context, _user.IdEmpresa).SelectDoctores(atencion.DoctorId);
            ViewBag.Paciente = atencion.Paciente;
            return View(atencion);
        }

        // GET: Atenciones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var atencion = await _context.Atencion.SingleOrDefaultAsync(m => m.Id == id);
            if (atencion == null)
            {
                return NotFound();
            }
            return View(atencion);
        }

        // POST: Atenciones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Comentario,DoctorId,Fecha,PacienteId,TimeStamp,Tipo")] Atencion atencion)
        {
            if (id != atencion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(atencion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AtencionExists(atencion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Pacientes", new { id = atencion.PacienteId });
            }
            return RedirectToAction("Details", "Pacientes", new { id = atencion.PacienteId });
        }

        // GET: Atenciones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var atencion = await _context.Atencion.SingleOrDefaultAsync(m => m.Id == id);
            if (atencion == null)
            {
                return NotFound();
            }

            return View(atencion);
        }

        // POST: Atenciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var atencion = await _context.Atencion.SingleOrDefaultAsync(m => m.Id == id);
            _context.Atencion.Remove(atencion);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool AtencionExists(int id)
        {
            return _context.Atencion.Any(e => e.Id == id);
        }
    }
}

src/clinical/Views/Atenciones/Create.cshtml
@model clinical.Models.Atencion

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Atencion</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Adjunto" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Adjunto" class="form-control" />
                <span asp-validation-for="Adjunto" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Comentario" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Comentario" class="form-control" />
                <span asp-validation-for="Comentario" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DoctorId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DoctorId" class="form-control" />
                <span asp-validation-for="DoctorId" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Fecha" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PacienteId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PacienteId" class="form-control" />
                <span asp-validation-for="PacienteId" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="TimeStamp" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="TimeStamp" class="form-control" />
                <span asp-validation-for="TimeStamp" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Tipo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/clinical/Views/Atenciones/Delete.cshtml
@model clinical.Models.Atencion

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Atencion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Adjunto)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Adjunto)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Comentario)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DoctorId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DoctorId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PacienteId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PacienteId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/clinical/Views/Atenciones/Details.cshtml
@model clinical.Models.Atencion

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Atencion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Adjunto)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Adjunto)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Comentario)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DoctorId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DoctorId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PacienteId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PacienteId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/clinical/Views/Atenciones/Edit.cshtml
@model clinical.Models.Atencion

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Atencion</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Adjunto" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Adjunto" class="form-control" />
                <span asp-validation-for="Adjunto" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Comentario" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Comentario" class="form-control" />
                <span asp-validation-for="Comentario" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DoctorId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DoctorId" class="form-control" />
                <span asp-validation-for="DoctorId" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Fecha" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PacienteId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PacienteId" class="form-control" />
                <span asp-validation-for="PacienteId" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="TimeStamp" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="TimeStamp" class="form-control" />
                <span asp-validation-for="TimeStamp" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Tipo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/clinical/Views/Atenciones/Index.cshtml
@model IEnumerable<clinical.Models.Atencion>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Comentario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoctorId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PacienteId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimeStamp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Comentario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PacienteId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeStamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

src/clinical/Views/Atenciones/_Create.cshtml
@model clinical.Models.Atencion

@{
    Layout = null;
    ViewData["Title"] = "Nueva Atencion";
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel"><span class="fa fa-plus-circle"></span> Nueva Atencion <b>@ViewBag.Paciente.NombreCompleto</b> <small>@ViewBag.Paciente.Edad años, @ViewBag.Paciente.Ocupacion</small></h4>
</div>
<form asp-action="Create" asp-controller="Atenciones">
    <div class="modal-body">
        <!--<div class="row">
            <div class="col-sm-12">
                    <h4></h4>
            </div>
        </div>-->
        <input type="hidden" asp-for="PacienteId" value="@ViewBag.PacienteId" />
        <div class="form-horizontal">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="DoctorId" class="col-sm-2 control-label"></label>
                        <div class="col-sm-10">
                            <select asp-for="DoctorId" asp-items="ViewBag.Doctores" class="form-control">
                                <option disabled selected>Selecciona...</option>
                            </select>
                            <span asp-validation-for="DoctorId" class="text-danger" />
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Fecha" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input asp-for="Fecha" class="form-control pull-right datepicker" value="@DateTime.Now.ToString("dd/MM/yyyy")" placeholder="DD/MM/AAAA" />
                            </div>
                            <span asp-validation-for="Fecha" class="text-danger" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Comentario" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <textarea asp-for="Comentario" rows="15" class="form-control noresize textarea"></textarea>
                    <span asp-validation-for="Comentario" class="text-danger" />
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <input type="submit" value="Guardar" class="btn btn-primary"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/clinical/Views/Atenciones/_Edit.cshtml
@model clinical.Models.Atencion

@{
    Layout = null;
    ViewData["Title"] = "Editar Atencion";
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Editar Atención <b>@ViewBag.Paciente.NombreCompleto</b> <small>@ViewBag.Paciente.Edad años, @ViewBag.Paciente.Ocupacion</small></h4>
</div>
<form asp-action="Edit" asp-controller="Atenciones" asp-route-id="@Model.Id">
    <div class="modal-body">
        <input type="hidden" asp-for="PacienteId" value="@ViewBag.PacienteId" />
        <div class="form-horizontal">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="DoctorId" class="col-sm-2 control-label"></label>
                        <div class="col-sm-10">
                            <select asp-for="DoctorId" asp-items="ViewBag.Doctores" class="form-control">
                                <option disabled selected>Selecciona...</option>
                            </select>
                            <span asp-validation-for="DoctorId" class="text-danger" />
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Fecha" class="col-md-2 control-label"></label>
                        <div class="col-md-10">
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input asp-for="Fecha" class="form-control pull-right datepicker" value="@Model.Fecha.ToString("dd/MM/yyyy")" placeholder="DD/MM/AAAA" />
                            </div>
                            <span asp-validation-for="Fecha" class="text-danger" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Comentario" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <textarea asp-for="Comentario" rows="6" class="form-control noresize textarea"></textarea>
                    <span asp-validation-for="Comentario" class="text-danger" />
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <input type="submit" value="Guardar" class="btn btn-primary"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}