src/clinical/Controllers/AdjuntoController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using clinical.Models.HomeViewModels;
using clinical.Data;
using clinical.Models;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System.IO;

namespace clinical.Controllers
{
    public class AdjuntoController : Controller
    {
        private readonly ApplicationDbContext _context;
        private ApplicationUser _user;

        public AdjuntoController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            var userId = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            _user = _context.Users.FirstOrDefault(u => u.Id == userId);
        }

        public async Task<IActionResult> Download(int id)
        {
            var file = await _context.Adjunto.Include(a => a.Paciente).SingleOrDefaultAsync(a => a.Id == id && a.Paciente.IdEmpresa.Equals(_user.IdEmpresa));
            if (file != null)
            {
                var stream = new MemoryStream();
                stream.Write(file.Archivo, 0, file.Archivo.Length);
                stream.Position = 0;
                return new FileStreamResult(stream, file.ContentType);
            }
            return NotFound("Archivo no encontrado");
        }

        public async Task<IActionResult> DownloadHistorical(int id)
        {
            var file = await _context.AdjuntoHistorico.Include(a => a.Paciente).SingleOrDefaultAsync(a => a.Id == id && a.Paciente.IdEmpresa.Equals(_user.IdEmpresa));
            if (file != null)
            {
                var stream = new MemoryStream();
                stream.Write(file.Archivo, 0, file.Archivo.Length);
                stream.Position = 0;
                return new FileStreamResult(stream, file.ContentType);
            }
            return NotFound("Archivo no encontrado");
        }
    }
}

src/clinical/Controllers/DoctoresController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using clinical.Data;
using clinical.Helpers;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;

namespace clinical.Models
{
    public class DoctoresController : Controller
    {
        private readonly ApplicationDbContext _context;
        private ApplicationUser _user;

        public DoctoresController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            var userId = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            _user = _context.Users.FirstOrDefault(u => u.Id == userId);
        }

        // GET: Doctores
        public async Task<IActionResult> Index()
        {
            return View(await _context.Doctor.Where(d => d.IdEmpresa.Equals(_user.IdEmpresa)).ToListAsync());
        }

        // GET: Doctores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctor.Where(d => d.IdEmpresa.Equals(_user.IdEmpresa)).Include(d => d.Pacientes).Include(d => d.Atenciones).ThenInclude(a => a.Paciente).SingleOrDefaultAsync(m => m.Id == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // GET: Doctores/Create
        public IActionResult Create()
        {
            ViewBag.Especialidades = new DoctoresHelper(_context, _user.IdEmpresa).SelectEspecialidad();
            return View();
        }

        // POST: Doctores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ApMaterno,ApPaterno,Email,Especialidad,Nombre,Rut,Telefono,FecNacimiento,Sexo")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                doctor.IdEmpresa = _user.IdEmpresa;
                _context.Add(doctor);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", new { id = doctor.Id });
            }
            return View(doctor);
        }

        // GET: Doctores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctor.SingleOrDefaultAsync(m => m.Id == id);
            if (doctor == null)
            {
                return NotFound();
            }
            ViewBag.Especialidades = new DoctoresHelper(_context, _user.IdEmpresa).SelectEspecialidad(doctor.Especialidad);
            return View(doctor);
        }

        // POST: Doctores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ApMaterno,ApPaterno,Email,Especialidad,Nombre,Rut,Telefono,FecNacimiento,Sexo")] Doctor doctor)
        {
            if (id != doctor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    doctor.IdEmpresa = _user.IdEmpresa;
                    _context.Update(doctor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoctorExists(doctor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new { id = doctor.Id });
            }
            return View(doctor);
        }

        // GET: Doctores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctor.SingleOrDefaultAsync(m => m.Id == id && m.IdEmpresa.Equals(_user.IdEmpresa));
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // POST: Doctores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var doctor = await _context.Doctor.SingleOrDefaultAsync(m => m.Id == id && m.IdEmpresa.Equals(_user.IdEmpresa));
            _context.Doctor.Remove(doctor);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool DoctorExists(int id)
        {
            return _context.Doctor.Any(e => e.Id == id && e.IdEmpresa.Equals(_user.IdEmpresa));
        }
    }
}

src/clinical/Controllers/PacientesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using clinical.Data;
using clinical.Models;
using clinical.Helpers;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.IO;

namespace clinical.Controllers
{
    public class PacientesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private ApplicationUser _user;

        public PacientesController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            var userId = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            _user = _context.Users.FirstOrDefault(u => u.Id == userId);
        }

        // GET: Pacientes
        public async Task<IActionResult> Index()
        {
            ViewData["BreadCrumbLevel1"] = "Pacientes";
            ViewData["BreadCrumbLevel1Link"] = "/Pacientes";
            return View(await _context.Paciente.Where(p => p.IdEmpresa.Equals(_user.IdEmpresa)).Include(paciente => paciente.Doctor).ToListAsync());
        }

        // GET: Pacientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewData["BreadCrumbLevel1"] = "Pacientes";
            ViewData["BreadCrumbLevel1Link"] = "/Pacientes";
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _context.Paciente.SingleOrDefaultAsync(m => m.Id == id && m.IdEmpresa.Equals(_user.IdEmpresa));
            if (paciente == null)
            {
                return NotFound();
            }

            paciente.Adjuntos = await _context.Adjunto.Where(a => a.PacienteId == id).Select(a => new Adjunto{ Id = a.Id, Nombre = a.Nombre}).ToListAsync();
            paciente.AdjuntosHistoricos = await _context.AdjuntoHistorico.Where(a => a.PacienteId == id).Select(a => new AdjuntoHistorico
            {
                Id = a.Id,
                Nombre = a.Nombre
            }).ToListAsync();
            paciente.Atenciones = await _context.Atencion.Where(a => a.PacienteId == id).Include(a => a.Doctor).OrderByDescending(a => a.TimeStamp).ThenBy(a => a.Id).ToListAsync();

            return View(paciente);
        }

        // GET: Pacientes/Create
        public IActionResult Create()
        {
            ViewBag.Doctores = new DoctoresHelper(_context, _user.IdEmpresa).SelectDoctores();
            var pacienteHelper = new PacientesHelper(_context);
            ViewBag.Previsiones = pacienteHelper.SelectPrevision();
            ViewBag.Estados = pacienteHelper.SelectEstadoCivil();
            return View();
        }

        // POST: Pacientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ApMaterno,ApPaterno,Direccion,DoctorId,Edad,EstadoCivil,FecNacimiento,IdEmpresa,Nombre,Prevision,Rut,Sexo,Email,Telefono,Ocupacion")] Paciente paciente)
        {
            if (PacienteExists(paciente.Rut))
            {
                ModelState.AddModelError("Rut","El Paciente " + paciente.Rut + " ya se encuentra registrado.");
            }
            if (ModelState.IsValid)
            {
                paciente.IdEmpresa = _user.IdEmpresa;
                _context.Add(paciente);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", new { id = paciente.Id });
            }
            return View(paciente);
        }

        // GET: Pacientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _context.Paciente.SingleOrDefaultAsync(m => m.Id == id);
            if (paciente == null)
            {
                return NotFound();
            }
            
            ViewBag.Doctores = new DoctoresHelper(_context, _user.IdEmpresa).SelectDoctores(paciente.DoctorId);
            var pacienteHelper = new PacientesHelper(_context);
            ViewBag.Previsiones = pacienteHelper.SelectPrevision(paciente.Prevision);
            ViewBag.Estados = pacienteHelper.SelectEstadoCivil(paciente.EstadoCivil);
            return View(paciente);
        }

        // POST: Pacientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ApMaterno,ApPaterno,Direccion,DoctorId,Edad,EstadoCivil,FecNacimiento,IdEmpresa,Nombre,Prevision,Rut,Sexo,Email,Telefono,Ocupacion")] Paciente paciente)
        {
            if (id != paciente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    paciente.IdEmpresa = _user.IdEmpresa;
                    _context.Update(paciente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PacienteExists(paciente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new { id = paciente.Id });
            }
            return View(paciente);
        }

        // GET: Pacientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _context.Paciente.SingleOrDefaultAsync(m => m.Id == id && m.IdEmpresa.Equals(_user.IdEmpresa));
            if (paciente == null)
            {
                return NotFound();
            }

            return View(paciente);
        }

        // POST: Pacientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var paciente = await _context.Paciente.SingleOrDefaultAsync(m => m.Id == id && m.IdEmpresa.Equals(_user.IdEmpresa));
            _context.Paciente.Remove(paciente);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool PacienteExists(int id)
        {
            return _context.Paciente.Any(e => e.Id == id && e.IdEmpresa.Equals(_user.IdEmpresa));
        }

        private bool PacienteExists(string rut)
        {
            return _context.Paciente.Any(e => e.Rut == rut && e.IdEmpresa.Equals(_user.IdEmpresa));
        }

        [HttpPost]
        public async Task<IActionResult> Upload(int id)
        {
            var files = Request.Form.Files;
            foreach (var file in files)
            {
                if (file.Length > 0)
                {
                    // TODO: Do domething with the files
                    var adjunto = new Adjunto {
                        Nombre = file.FileName,
                        ContentType = file.ContentType,
                        Archivo = FileHelper.ConvertToBytes(file),
                        PacienteId = id
                    };

                    _context.Add(adjunto);
                }

            }
            await _context.SaveChangesAsync();
            return Json(new { Status = "Ok" });
        }

        [HttpPost]
        public async Task<IActionResult> UploadHistorical(int id)
        {
            var files = Request.Form.Files;
            foreach (var file in files)
            {
                if (file.Length > 0)
                {
                    // TODO: Do domething with the files
                    var adjunto = new AdjuntoHistorico
                    {
                        Nombre = file.FileName,
                        ContentType = file.ContentType,
                        Archivo = FileHelper.ConvertToBytes(file),
                        PacienteId = id
                    };

                    _context.Add(adjunto);
                }

            }
            await _context.SaveChangesAsync();
            return Json(new { Status = "Ok" });
        }

    }
}

src/clinical/Views/Pacientes/Delete.cshtml
@model clinical.Models.Paciente

@{
    ViewData["Title"] = "Borrar Paciente";
}

<div class="row">
    <div class="col-sm-4">
        <div class="box box-info">
            <div class="box-body box-profile">
                @Html.GravatarImage(Model.Email, "profile-user-img img-responsive img-circle", 80, GravatarHtmlHelper.DefaultImage.MysteryMan)

                <h3 class="profile-username text-center">@Html.DisplayFor(model => model.NombreCompleto)</h3>

                <p class="text-muted text-center">@Html.DisplayFor(model => model.Edad) @Html.Raw("a&ntilde;os")</p>

                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                        <b>Rut</b> <a class="pull-right">@Html.DisplayFor(model => model.Rut)</a>
                    </li>
                    <li class="list-group-item">
                        <i class="fa fa-envelope"></i> <b>@Html.DisplayNameFor(model => model.Email)</b> <span class="pull-right">@Html.DisplayFor(model => model.Email)</span>
                    </li>
                    <li class="list-group-item">
                        <b><i class="fa fa-phone"></i> @Html.DisplayNameFor(model => model.Telefono)</b> <a href="tel:@Html.DisplayFor(model => model.Telefono)" class="pull-right">@Html.DisplayFor(model => model.Telefono)</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Antecedentes</h3>
            </div>
            <div class="box-body">
                <strong>
                    <i class="fa fa-user-md"></i> Doctor
                </strong>
                <a asp-controller="Doctores" asp-action="Details" asp-route-id="@Model.DoctorId" class="pull-right">@Html.DisplayFor(model => model.Doctor.NombreCompleto)</a>
                <hr />
                <strong>
                    @Html.DisplayNameFor(model => model.Prevision)
                </strong>
                <a class="pull-right">@Html.DisplayFor(model => model.Prevision)</a>
                <hr />
                <strong><i class="fa fa-map-marker margin-r-5"></i> @Html.DisplayNameFor(model => model.Direccion)</strong>
                <p class="text-muted">@Html.DisplayFor(model => model.Direccion)</p>
                <hr />
                <strong>
                    @Html.DisplayNameFor(model => model.FecNacimiento)
                </strong>
                <a class="pull-right">@Html.DisplayFor(model => model.FecNacimiento)</a>
                <hr />
                <strong>
                    @Html.DisplayNameFor(model => model.Sexo)
                </strong>
                <a class="pull-right">@Html.DisplayFor(model => model.Sexo)</a>
                <hr />
                <strong>
                    @Html.DisplayNameFor(model => model.EstadoCivil)
                </strong>
                <a class="pull-right">@Html.DisplayFor(model => model.EstadoCivil)</a>
            </div>
        </div>

    </div>
    <div class="col-sm-8">
        <div class="box box-info">
            <div class="box-body">
                <div class="row">
                    <div class="col-xs-12">
                        <h4>Estas seguro que quieres eliminar este Paciente?</h4>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <form asp-action="Delete">
                            <a asp-action="Index" class="btn btn-lg btn-default">Cancelar</a>
                            &emsp;
                            <input type="submit" value="Borrar" class="btn btn-lg btn-danger" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/clinical/Views/Pacientes/Details.cshtml
@model clinical.Models.Paciente

@{
    ViewData["Title"] = "Paciente";
}

<div class="row">
    <div class="col-sm-4">
        <div class="box box-info">
            <div class="box-body box-profile">
                <input id="PacienteId" type="hidden" value="@Model.Id" />
                @Html.GravatarImage(Model.Email, "profile-user-img img-responsive img-circle",80,GravatarHtmlHelper.DefaultImage.MysteryMan)

                <h3 class="profile-username text-center">@Html.DisplayFor(model => model.NombreCompleto)</h3>

                <p class="text-muted text-center">@Html.DisplayFor(model => model.Edad) @Html.Raw("a&ntilde;os")</p>

                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                        <b>Rut</b> <a class="pull-right">@Html.DisplayFor(model => model.Rut)</a>
                    </li>
                    <li class="list-group-item">
                        <b>@Html.DisplayNameFor(model => model.Prevision)</b> <a class="pull-right">@Html.DisplayFor(model => model.Prevision)</a>
                    </li>
                    <li class="list-group-item">
                         <b>@Html.DisplayNameFor(model => model.Ocupacion)</b> <a class="pull-right">@Html.DisplayFor(model => model.Ocupacion)</a>
                    </li>
                    <li class="list-group-item">
                        <i class="fa fa-envelope"></i> <b>@Html.DisplayNameFor(model => model.Email)</b> <span class="pull-right">@Html.DisplayFor(model => model.Email)</span>
                    </li>
                    <li class="list-group-item">
                        <b><i class="fa fa-phone"></i> @Html.DisplayNameFor(model => model.Telefono)</b> <a href="tel:@Html.DisplayFor(model => model.Telefono)" class="pull-right">@Html.DisplayFor(model => model.Telefono)</a>
                    </li>
                </ul>

                <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary btn-block"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> <b>Editar</b></a>
            </div>
        </div>
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Antecedentes</h3>
            </div>
            <div class="box-body">
                <strong>
                    <i class="fa fa-user-md"></i> Doctor
                </strong>
                <a asp-controller="Doctores" asp-action="Details" asp-route-id="@Model.DoctorId" class="pull-right">@Html.DisplayFor(model => model.Doctor.NombreCompleto)</a>
                <hr />
                <strong><i class="fa fa-map-marker margin-r-5"></i> @Html.DisplayNameFor(model => model.Direccion)</strong>
                <p class="text-muted">@Html.DisplayFor(model => model.Direccion)</p>
                <hr />
                <strong>
                    @Html.DisplayNameFor(model => model.FecNacimiento)
                </strong>
                <a class="pull-right">@Html.DisplayFor(model => model.FecNacimiento)</a>
                <hr />
                <div class="row">
                    <div class="col-xs-6">
                        <strong>
                            @Html.DisplayNameFor(model => model.EstadoCivil)
                        </strong>
                        <a class="pull-right">@Html.DisplayFor(model => model.EstadoCivil)</a>
                    </div>
                    <div class="col-xs-6">
                        <strong>
                            @Html.DisplayNameFor(model => model.Sexo)
                        </strong>
                        <a class="pull-right">@Html.DisplayFor(model => model.Sexo)</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">@Html.DisplayNameFor(model => model.Adjuntos) <i class="fa fa-paperclip"></i></h3>
            </div>
            <div class="box-body">
                @if (Model.Adjuntos.Any())
                {
                    foreach (var adjunto in Model.Adjuntos.OrderByDescending(a => a.Id))
                    {
                        <i class="fa fa-paperclip"></i> <a target="_blank" asp-controller="Adjunto" asp-action="Download" asp-route-id="@adjunto.Id">@adjunto.Nombre</a><br>
                    }
                    <hr />
                }
                <div class="row">
                    <div class="col-xs-12">
                        <form asp-route-id="@Model.Id" asp-action="Upload" asp-controller="Pacientes" method="post" enctype="multipart/form-data" class="dropzone">
                            <div class="dz-message">
                                <i class="fa fa-cloud-upload"></i> Arrastra aqui tus archivos.
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">@Html.DisplayNameFor(model => model.AdjuntosHistoricos) <i class="fa fa-paperclip"></i></h3>
            </div>
            <div class="box-body">
                @if (Model.AdjuntosHistoricos.Any())
                {
                    foreach (var adjunto in Model.AdjuntosHistoricos.OrderByDescending(a => a.Id))
                    {
                        <i class="fa fa-paperclip"></i> <a target="_blank" asp-controller="Adjunto" asp-action="DownloadHistorical" asp-route-id="@adjunto.Id">@adjunto.Nombre</a><br>
                    }
                    <hr />
                }
                <div class="row">
                    <div class="col-xs-12">
                        <form asp-route-id="@Model.Id" asp-action="UploadHistorical" asp-controller="Pacientes" method="post" enctype="multipart/form-data" class="dropzone">
                            <div class="dz-message">
                                <i class="fa fa-cloud-upload"></i> Agregar Ficha.
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="col-sm-8">

        <h4>Historia Clinica</h4>
        <ul class="timeline">
            <!-- timeline time label -->
            <li>
                <i class="fa fa-calendar-plus-o bg-aqua" aria-hidden="true"></i>
                <div class="margin-left-3x">
                    <a id="AgregarAtencion" class="btn btn-info" data-toggle="modal" data-target="#crearAtencionModal"> Agregar Atencion</a>
                </div>
            </li>
            <!-- /.timeline-label -->
            @if (Model.Atenciones.Any())
            {
                foreach (var atencion in Model.Atenciones.OrderByDescending(a => a.Fecha).ThenByDescending(a => a.Id))
                {
                    <li>
                        <i class="fa fa-medkit bg-blue"></i>

                        <div class="timeline-item">
                            <span class="time">
                                <i class="fa fa-clock-o"></i> @atencion.Fecha.ToString("dd/MMM/yyyy")
                                &nbsp;
                                <a class="btn btn-xs btn-default editAtencion" data-toggle="modal" data-target="#editarAtencionModal" data-id="@atencion.Id"><i class="fa fa-pencil-square-o"></i></a>
                            </span>

                            <h3 class="timeline-header">
                                Atenci&oacute;n realizada por <a asp-controller="Doctores" asp-action="Details" asp-route-id="@atencion.DoctorId">@atencion.Doctor.NombreCompleto</a>
                            </h3>

                            <div class="timeline-body">
                                @Html.Raw(atencion.Comentario)
                            </div>
                        </div>

                    </li>
                }
            }
            else
            {
                <li>
                    <i class="fa fa-info bg-yellow"></i>

                    <div class="timeline-item">
                        <span class="time"><i class="fa fa-clock-o"></i> @DateTime.Now.ToString("dd/MMM/yyyy")</span>
                        <h3 class="timeline-header"><a href="#">@Model.NombreCompleto</a> no registra atenciones</h3>
                    </div>

                </li>
            }

            <li>
                <i class="fa fa-clock-o bg-gray"></i>
            </li>
        </ul>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="crearAtencionModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div id="crearAtencionModalContent" class="modal-content">
            <p class="margin-bottom text-center">
                <i class="fa fa-3x fa-spin fa-refresh"></i>
            </p>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="editarAtencionModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div id="editarAtencionModalContent" class="modal-content">
            <p class="margin-bottom text-center">
                <i class="fa fa-3x fa-spin fa-refresh"></i>
            </p>
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/lib/dropzone/dropzone.js"></script>
}